spring:
    datasource:
        password: postgres
        username: postgres
        driver: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/booking
        leakDetectionThreshold: 240000
        maximumPoolSize: 10
    application:
        name: booking-service
        profiles:
            active: local
    data:
        jpa:
            repositories:
                enabled: true
                bootstrap-mode: default
    jpa:
        open-in-view: false
        database: POSTGRESQL
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                enable_lazy_load_no_trans: true
                jdbc:
                    batch_size: 30
logging:
    level:
        org:
            springframework: debug